# Generated by Django 4.2.3 on 2024-06-19 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0002_choise_submission_question_choise_question'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Choise',
            new_name='Choice',
        ),
        migrations.RenameField(
            model_name='choice',
            old_name='choise',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='grade_point',
            new_name='grade',
        ),
    ]
